# Generated by Django 5.1.7 on 2026-02-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descrição',
        ),
    ]
