# Generated by Django 5.1.7 on 2026-02-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='descrição',
            new_name='description',
        ),
    ]
