# Generated by Django 5.1.7 on 2026-02-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_categoria_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
