# Generated by Django 5.2.15 on 2026-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
