# Generated by Django 5.2.15 on 2026-08-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_editora_cidade_alter_editora_email'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_foto', to='uploader.image'),
        ),
    ]
